import type {
  ModuleId, ModulePayload, Project, Variant,
} from "@/lib/types";
import { MODULE_BY_ID, MODULES } from "@/data/modules";
import { STANCE_WORDS } from "@/lib/generators/ctx";

/**
 * Brand.md and Design.md.
 *
 * The rule the whole app is built around applies hardest here: only approved
 * modules are written as fact. Anything still in draft is listed by name at
 * the bottom under "Not yet approved", so whoever picks this file up knows
 * exactly how much of it a human has signed off.
 */

function approvedPayload(project: Project, id: ModuleId): ModulePayload | null {
  const state = project.modules[id];
  if (!state || state.status !== "approved" || !state.approvedVariantId) return null;
  const variant = state.variants.find((v: Variant) => v.id === state.approvedVariantId);
  return variant ? variant.payload : null;
}

function h(level: number, text: string): string {
  return `${"#".repeat(level)} ${text}`;
}

function bullets(items: string[]): string {
  return items.map((i) => `- ${i}`).join("\n");
}

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(" | ")} |`;
  const rule = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
  return [head, rule, body].join("\n");
}

function frontMatter(project: Project, kind: "Brand" | "Design"): string {
  const approvedCount = MODULES.filter((m) => project.modules[m.id]?.status === "approved").length;
  return [
    "---",
    `document: ${kind}.md`,
    `brand: ${project.brief.brandName || "Untitled"}`,
    `generated: ${new Date().toISOString().slice(0, 10)}`,
    `approved_modules: ${approvedCount} of ${MODULES.length}`,
    "source: design studio — approved modules only",
    "---",
  ].join("\n");
}

function notApproved(project: Project, ids: ModuleId[]): string {
  const pending = ids.filter((id) => project.modules[id]?.status !== "approved");
  if (pending.length === 0) return "";
  return [
    "",
    h(2, "Not yet approved"),
    "",
    "These sections exist in the studio but nobody has signed them off, so they are deliberately absent above. Treat any claim about them as unverified.",
    "",
    bullets(pending.map((id) => MODULE_BY_ID[id].title)),
  ].join("\n");
}

/* ================================================================ */
/* Brand.md — strategy, positioning and language                     */
/* ================================================================ */

const BRAND_MODULES: ModuleId[] = [
  "story", "mission", "vision", "offering", "market", "audience",
  "competition", "differentiation", "expose", "tone", "social", "website",
];

export function buildBrandMd(project: Project): string {
  const { brief } = project;
  const name = brief.brandName || "Untitled brand";
  const out: string[] = [frontMatter(project, "Brand"), "", h(1, `${name} — Brand`), ""];

  out.push(
    "Written for a person first and an assistant second. Everything below has been approved by a human in the studio; anything that was not is listed at the end.",
    "",
    h(2, "At a glance"),
    "",
    table(
      ["Field", "Value"],
      [
        ["Name", name],
        ["Sector", brief.sector || "—"],
        ["Based", brief.location || "—"],
        ["Working since", brief.foundedYear || "—"],
        ["Price position", `${STANCE_WORDS[brief.priceStance].adj} — ${STANCE_WORDS[brief.priceStance].note}`],
        ["Personality", brief.traits.join(", ") || "—"],
      ],
    ),
    "",
  );

  for (const id of BRAND_MODULES) {
    const payload = approvedPayload(project, id);
    if (!payload) continue;
    out.push(h(2, MODULE_BY_ID[id].title), "", renderPayload(payload), "");
  }

  out.push(
    h(2, "How to use this file"),
    "",
    bullets([
      "Paste it into an assistant as a system prompt to brief it on the brand before it writes anything.",
      "Hand it to a freelancer on day one instead of a two-hour call.",
      "Keep it in the repository next to the code, so the copy and the product cannot drift apart.",
      "When a section changes in the studio, re-export. Do not edit this file by hand — it will be overwritten.",
    ]),
    notApproved(project, BRAND_MODULES),
  );

  return out.filter((line) => line !== undefined).join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";
}

/* ================================================================ */
/* Design.md — the visual system                                     */
/* ================================================================ */

const DESIGN_MODULES: ModuleId[] = [
  "lookfeel", "logo", "palette", "typography", "packaging", "marketing", "social", "website",
];

export function buildDesignMd(project: Project): string {
  const { brief } = project;
  const name = brief.brandName || "Untitled brand";
  const out: string[] = [frontMatter(project, "Design"), "", h(1, `${name} — Design`), ""];

  out.push(
    "The visual system, written so it can be implemented without a call. Values are exact; judgement calls are marked as such.",
    "",
  );

  const palette = approvedPayload(project, "palette");
  const type = approvedPayload(project, "typography");

  if (palette?.kind === "palette" || type?.kind === "typography") {
    out.push(h(2, "Design tokens"), "", "```css", ":root {");
    if (palette?.kind === "palette") {
      for (const s of palette.data.swatches) {
        out.push(`  --color-${slug(s.name)}: ${s.hex};`);
      }
    }
    if (type?.kind === "typography") {
      out.push(`  --font-primary: ${type.data.primary.stack};`);
      out.push(`  --font-secondary: ${type.data.secondary.stack};`);
      for (const level of type.data.levels) {
        out.push(`  --type-${slug(level.level)}: ${level.size}/${level.lineHeight};`);
      }
    }
    out.push("}", "```", "");
  }

  for (const id of DESIGN_MODULES) {
    const payload = approvedPayload(project, id);
    if (!payload) continue;
    out.push(h(2, MODULE_BY_ID[id].title), "", renderPayload(payload), "");
  }

  out.push(notApproved(project, DESIGN_MODULES));
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";
}

function slug(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

/* ================================================================ */
/* Payload rendering                                                 */
/* ================================================================ */

function renderPayload(payload: ModulePayload): string {
  switch (payload.kind) {
    case "prose":
      return payload.data.paragraphs.join("\n\n");

    case "statements":
      return [
        payload.data.intro,
        "",
        payload.data.items
          .map((item) => {
            const parts = [`${h(3, item.label)}`, "", `**${item.statement}**`, "", item.detail];
            if (item.sayThis) parts.push("", `Say: “${item.sayThis}”`);
            if (item.counterExample) parts.push(`Not: “${item.counterExample}”`);
            if (item.bannedWords?.length) parts.push("", `Banned: ${item.bannedWords.map((w) => `\`${w}\``).join(", ")}`);
            return parts.join("\n");
          })
          .join("\n\n"),
      ].join("\n");

    case "palette":
      return [
        `**${payload.data.name}** — ${payload.data.rationale}`,
        "",
        table(
          ["Name", "Role", "HEX", "RGB", "CMYK", "On white", "Use"],
          payload.data.swatches.map((s) => [
            s.name, s.role, s.hex, s.rgb.join(", "), s.cmyk.join(", "),
            `${s.contrastOnWhite}:1`, s.usage,
          ]),
        ),
        "",
        `**Pairing rule.** ${payload.data.pairingRule}`,
      ].join("\n");

    case "typography":
      return [
        `**Class.** ${payload.data.className} — ${payload.data.classNote}`,
        "",
        `**Primary.** ${payload.data.primary.name} (${payload.data.primary.weights.join(", ")})`,
        `**Secondary.** ${payload.data.secondary.name} (${payload.data.secondary.weights.join(", ")})`,
        `**Scale.** ${payload.data.scaleRatio}`,
        "",
        table(
          ["Level", "Weight", "Size", "Line height", "Tracking", "Use"],
          payload.data.levels.map((l) => [l.level, l.weight, l.size, l.lineHeight, l.tracking, l.use]),
        ),
        "",
        bullets(payload.data.rules),
      ].join("\n");

    case "logo": {
      const chosen = payload.data.routes.find((r) => r.id === payload.data.chosenRouteId) ?? payload.data.routes[0];
      const lines = [];
      if (payload.data.uploadedMark) {
        lines.push(`**Working from client artwork.** ${payload.data.uploadedName ?? "Uploaded mark"} — the routes below were not used.`, "");
      }
      if (chosen) {
        lines.push(
          `**Route.** ${chosen.name}`, "",
          `**Construction.** ${chosen.construction}`, "",
          `**Why.** ${chosen.rationale}`, "",
          table(["Rule", "Value"], [
            ["Clearspace", chosen.clearspace],
            ["Minimum size", chosen.minSize],
            ["Variants supplied", chosen.variants.join(", ")],
          ]),
        );
      }
      lines.push("", payload.data.wordmarkNote);
      return lines.join("\n");
    }

    case "audience":
      return [
        payload.data.read,
        "",
        payload.data.personas
          .map((p) =>
            [
              h(3, `${p.name} — ${p.archetypeLabel}`),
              "",
              bullets(p.traits.map((t, i) => `${i + 1}. ${t}`)),
              "",
              table(["Field", "Value"], [
                ["Age", p.age], ["Location", p.location], ["Also buys", p.alsoBuys.join(", ")],
              ]),
              "",
              `**Motivations.**\n${bullets(p.motivations)}`,
              "",
              `**Challenges.**\n${bullets(p.challenges)}`,
              "",
              `**Why this brand.**\n${bullets(p.whyThisBrand)}`,
              "",
              `**Buying behaviour.**\n${bullets(p.buyingBehaviour)}`,
              "",
              `**Where they are.**\n${bullets(p.socialBehaviour)}`,
            ].join("\n"),
          )
          .join("\n\n"),
      ].join("\n");

    case "market":
      return [
        `**${payload.data.headline}**`, "", payload.data.summary, "",
        table(["Figure", "What it is", "Note"], payload.data.figures.map((f) => [f.value, f.label, f.note])),
        "",
        h(3, "Segments"), "",
        table(["Segment", "Share", "Note"], payload.data.segments.map((s) => [s.name, `${s.share}%`, s.note])),
        "",
        h(3, "What is shifting"), "", bullets(payload.data.shifts),
        "",
        h(3, "Sources"), "", bullets(payload.data.sources),
      ].join("\n");

    case "competition":
      return [
        payload.data.read, "",
        table(["Competitor", "Position", "Does well", "Leaves open", "Price"],
          payload.data.rows.map((r) => [r.name, r.position, r.doesWell, r.leavesOpen, r.priceBand])),
        "",
        `**Map axes.** ${payload.data.axes.x[0]} ↔ ${payload.data.axes.x[1]} against ${payload.data.axes.y[0]} ↔ ${payload.data.axes.y[1]}.`,
      ].join("\n");

    case "differentiation":
      return [
        `**${payload.data.claim}**`, "",
        h(3, "Proof"), "",
        payload.data.proofs.map((p) => `- **${p.proof}** ${p.evidence}`).join("\n"),
        "",
        `**Only we can say this because.** ${payload.data.onlyWeCan}`,
        "",
        h(3, "Not for"), "", bullets(payload.data.notFor),
      ].join("\n");

    case "offering":
      return [
        payload.data.line, "",
        payload.data.tiers.map((t) =>
          [`${h(3, `${t.name} — ${t.price}`)}`, "", `*${t.forWho}*`, "", bullets(t.includes)].join("\n"),
        ).join("\n\n"),
        "",
        h(3, "Where the edges are"), "", bullets(payload.data.boundaries),
      ].join("\n");

    case "lookfeel": {
      const chosen = payload.data.directions.find((d) => d.id === payload.data.chosenId) ?? payload.data.directions[0];
      return [
        `**Direction.** ${chosen.name} — ${chosen.adjectives.join(" · ")}`, "",
        chosen.description, "",
        table(["Aspect", "Rule"], [
          ["Surfaces", chosen.surfaces.join("; ")],
          ["Photography", chosen.photography],
          ["Motion", chosen.motion],
          ["Grid", payload.data.gridNote],
          ["Margins", payload.data.marginRule],
        ]),
        "",
        `Directions not taken: ${payload.data.directions.filter((d) => d.id !== chosen.id).map((d) => d.name).join(", ")}.`,
      ].join("\n");
    }

    case "packaging":
      return [
        table(["Aspect", "Spec"], [["Substrate", payload.data.substrate], ["Finish", payload.data.finish]]),
        "",
        payload.data.items.map((item) =>
          [`${h(3, item.name)}`, "", `*${item.format}*`, "", bullets(item.spec),
            item.copy ? `\nCopy: **${item.copy.headline}**${item.copy.sub ? ` / ${item.copy.sub}` : ""}` : ""].join("\n"),
        ).join("\n\n"),
        "",
        `**Unboxing.** ${payload.data.unboxingNote}`,
      ].join("\n");

    case "marketing":
      return [
        payload.data.layouts.map((l) =>
          [`${h(3, l.name)}`, "", `*${l.ratio}* — ${l.grid}`, "", bullets(l.hierarchy), "",
            `Headline: **${l.headline}**${l.sub ? `\n\nSub: ${l.sub}` : ""}`].join("\n"),
        ).join("\n\n"),
        "",
        h(3, "Rules that apply to every format"), "", bullets(payload.data.rules),
      ].join("\n");

    case "social":
      return [
        `**${payload.data.handle}** — ${payload.data.bio}`, "",
        h(3, "Content pillars"), "",
        table(["Pillar", "Share", "What it looks like"],
          payload.data.pillars.map((p) => [p.name, `${p.share}%`, p.example])),
        "",
        h(3, "Post formats"), "",
        payload.data.posts.map((p) => `- **${p.format}** — “${p.headline}” · ${p.caption}`).join("\n"),
        "",
        `**Banner.** ${payload.data.bannerNote}`,
        "",
        `**Cadence.** ${payload.data.cadence}`,
      ].join("\n");

    case "website":
      return [
        `**Navigation.** ${payload.data.navigation.join(" · ")}`, "",
        h(3, "Hero"), "",
        `Eyebrow: ${payload.data.hero.eyebrow}`,
        `\n# ${payload.data.hero.headline}\n`,
        payload.data.hero.sub,
        `\nPrimary action: **${payload.data.hero.primaryCta}** · Secondary: ${payload.data.hero.secondaryCta}`,
        "",
        h(3, "Sections"), "",
        payload.data.sections.map((s) => `**${s.kicker} — ${s.heading}**\n\n${s.body}`).join("\n\n"),
        "",
        `**Proof.** ${payload.data.proof}`,
        `**Footer.** ${payload.data.footerLine}`,
      ].join("\n");

    case "expose":
      return [
        `**${payload.data.oneLiner}**`, "",
        payload.data.paragraphs.join("\n\n"), "",
        table(["Field", "Value"], payload.data.atAGlance.map((r) => [r.label, r.value])),
        "",
        payload.data.pressLine,
      ].join("\n");

    default:
      return "";
  }
}
